const googleAPIKey ='AIzaSyCk1OL8EZAU8L4aVXFi3v16ocGDI0mcwVY';
const matchTypeKey = 'matchType';
const genderTypeKey ='genderType';
const availableDaysToPlayKey = 'availableDaysToPlay';
const isAvailableInMorningKey  = 'isAvailableInMorning';
const isAvailableDailyKey = 'isAvailableDaily';
const uploadedFilesKey = 'uploadedFiles';
const isReviewedKey = 'isReviewed';
const clubKey = 'club';
const chatClickTrackerCollection = 'chat_click_tracker';
const triggerTypeEmail ='email';
const triggerTypeMessage = 'message';
const playerTypeCoachValue ='Coach';
const playerTypeTennisValue = 'Tennis';
const playerTypePadelValue = 'Padel';
const playerTypePickleBallValue = 'Pickleball';
const willPartonImageUrl = 'https://media.licdn.com/dms/image/v2/D5603AQHuIuo9ug2BoQ/profile-displayphoto-shrink_800_800/B56ZSwAHRVGUAk-/0/1738119608113?e=1761177600&v=beta&t=2VkO0SYNJ6FaA1mQdVL_vnqgQu-MZN8UC9g19GBsRM0';