const googleAPIKey ='AIzaSyCk1OL8EZAU8L4aVXFi3v16ocGDI0mcwVY';
const matchTypeKey = 'matchType';
const genderTypeKey ='genderType';
const availableDaysToPlayKey = 'availableDaysToPlay';
const isAvailableInMorningKey  = 'isAvailableInMorning';
const isAvailableDailyKey = 'isAvailableDaily';
const uploadedFilesKey = 'uploadedFiles';
const isReviewedKey = 'isReviewed';
const clubKey = 'club';